# -*- mode: yaml -*-

jobs:
- job: linux_gcc
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      GCC:
        CXX: g++-8
        CC: gcc-8
  steps:
  - script: |
      mkdir build
      cd build
      cmake .. \
        -G Ninja \
        -DCMAKE_BUILD_TYPE=Debug \
    displayName: 'CMake'
  - script: |
      cd build
      ninja
    displayName: 'Build'
  - script: |
      cd build
      ctest -V
    displayName: 'Test'
